@startuml
'https://plantuml.com/class-diagram

class ComplexNumber {
    - double real
    - double imaginary

    + ComplexNumber(double real, double imaginary)
    + ComplexNumber(double real)
    + ComplexNumber plus(ComplexNumber c)
    + double getReal()
    + double getImaginary()
}

@enduml