@startuml
'https://plantuml.com/class-diagram


class ComplexNumber {
    - double real;
    - double imaginary;

    + ComplexNumber(double real, double imaginary);

    + ComplexNumber(double real);

    + {static} ComplexNumber sum(ComplexNumber c1, ComplexNumber c2);

    + double getReal();

    + double getImaginary();
}

@enduml