@startuml

class Point {
    - double x
    - double y

    + Point(double x, double y)
    + double distanceTo(Point otherPoint)
}

interface Figure {
    + double perimeter()
    + double area()
}

class Rectangle implements Figure {
    - Point corner1
    - Point corner2

    + Rectangle(Point corner1, Point corner2)
    + double perimeter()
    + double area()
    + double base()
    + double height()
}

class Triangle implements Figure {
    - Point corner1
    - Point corner2
    - Point corner3

    + Triangle(Point corner1, Point corner2, Point corner3)
    + double perimeter()
    + double area()
}

class Ellipse implements Figure {
    - Point center
    - double axisA
    - double axisB

    + Elipse(Point center, double axisA, double axisB)
    + double perimeter()
    + double area()
}

class Circle extends Ellipse {
    + Circle(Point center, double radius)
}

@enduml
