@startuml

abstract class Account {
    - int id
    - double balance

    + Account(int id);
    + double getBalance()
    + void deposit(double amount)
    # {abstract}boolean canExtract(double amount)
    + void extract(double amount)
}

class SavingsAccount implements Account {

    + CheckingAccount(int id, double overdraft)
    # boolean canExtract(double amount)
}

class CheckingAccount implements Account {
    - double overdraft

    + SavingsAccount(int id)
    # boolean canExtract(double amount)
}

@enduml