@startuml

interface Account {
    + int id
    + double balance

    + double getBalance()
    + void deposit()
    + void extract()
}

class SavingsAccount implements Account {
    + int id
    + double balance

    + double getBalance()
    + void deposit()
    + void extract()
}

class CheckingAccount implements Account {
    + int id
    + double balance

    + double getBalance()
    + void deposit()
    + void extract()
}

@enduml